# 日志
logging:
  level:
    com.shyoc.dao: info
  file:
    name: log/blog-prod.log
#端口号
server:
  port: 8001

spring:
  #redis
  redis:
    host: localhost
    port: 6379
    password: xxx
    timeout: 10000
    jedis:
      pool:
        max-active: 300
        max-idle: 100
        min-idle: 0
        max-wait: -1ms
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: xxx
    password: xxx
