spring:
  #    redis
  redis:
    host: xxx
    port: 6379
    password: xxx
  #    数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: xxx
    password: xxx
  devtools:
    restart:
      exclude:
# 日志
logging:
  level:
    com.shyoc: debug
  file:
    name: log/blog-dev.log
server:
  port: 8002